### ISSUE TITLE
Non-portable launcher prefix in python scripts

### ISSUE THREAD

**Issue by Araneidae** [PandABlocks/PandABlocks-FPGA#15]
The following scripts all start with `#!/bin/env` rather than `#!/usr/bin/env`.  This is not portable as many distributions don't install `env` in `/bin`.

* common/python/generate_app.py
* common/python/generate_hdl_timing.py
* common/python/parse_git_version.py
* common/python/timing_plot.py
* tests/test_python_sim_timing.py

I'm afraid that also numerous python scripts are launched with `dls-python` rather than `python2`, which is also not portable:

* common/python/generate_app.py
* common/python/generate_hdl_timing.py
* common/python/timing_plot.py
* tests/test_python_sim_timing.py

**Comment by thomascobb** [comment]
Fixed by #16
