### ISSUE TITLE
Rename SAMPLES -> GATE_DURATION and add NOMINAL_CLOCK

### ISSUE THREAD

**Issue by coretl** [PandABlocks/PandABlocks-FPGA#152]
As per https://github.com/PandABlocks/PandABlocks-server/issues/8#issuecomment-1724944170

NOMINAL_CLOCK should be hardcoded to 125e9. #150 will put actual numbers in it

**Comment by Araneidae** [comment]
You actually mean 125_000_000 of course (125e6 as an integer).

**Comment by Araneidae** [comment]
This is addressed by commits 26ffcfba86d095bed4e99794f5bbae63db45188c and eecb30e01623b8692db0d80c4e545cc0d730dc8f
