### ISSUE TITLE
Investigate mechanism to read built-in MAC addresses from Secure EEPROM on XU5 and XU6

### ISSUE THREAD

**Issue by glennchid** [PandABlocks/PandABlocks-FPGA#167]
Under petalinux u-boot reads MAC address from the Secure EEPROM and populates this in the device-tree <local_mac_address> field. In our build a random locally administered addresses is put in the device-tree by u-boot, which is later over-ridden in linux with the value in `/qspi/MAC` via `ifconfig`. The present work-around is to manually write the Enclustra-assigned MAC address to the QSPI.

I tried the following entry in the dts (copied from the petalinux generated dts):
```
&gem0 {
	local-mac-address = [ff ff ff ff ff ff];
};
```
but this did not work on its own, as more config is required in petallinux, see eg:
https://support.xilinx.com/s/question/0D52E00006hpQdiSAE/uboot-ethernet-mac-address-from-eeprom-petalinux-20202?language=en_US

**Comment by EmilioPeJu** [comment]
There are 2 pull requests dealing with this: https://github.com/PandABlocks/PandABlocks-FPGA/pull/186 and https://github.com/PandABlocks/PandABlocks-rootfs/pull/49

**Comment by EmilioPeJu** [comment]
Solved in the PRs I mentioned in my last comment
