### ISSUE TITLE
OUTENC does not work with QPERIOD set to 0 (8 ns)

### ISSUE THREAD

**Issue by tomtrafford** [PandABlocks/PandABlocks-FPGA#171]
When using an encoder Control card we have noticed that the QSTATE of the OUTENC block does not stabilise as expected when QPERIOD is set to 0. When reading the signal back into an INENC (through an encoder loopback cable) this introduces odd behaviour to the Value. This all works as expected when setting QPERIOD to 16 ns. 

There are currently no unit tests with QPERIOD set to '1'. 

Are there instances in production systems where QPERIOD is set to '0' or 8ns.

**Comment by glennchid** [comment]
The issues seems to be that the position tracking counter was taking two clock ticks up update and hence overshooting and oscillating around the set point when updated at the system clock frequency.

I have put a prospective fix on the branch:
https://github.com/PandABlocks/PandABlocks-FPGA/tree/171-outenc-does-not-work-with-qperiod-set-to-0-8-ns
@tomtrafford please can you try this?

**Comment by glennchid** [comment]
I have updated this again, as I discovered an issue where the output does not always update correctly, depending on the phase of the qenc_clk (as determined by the QPERIOD). To get around this involved changing the timing slightly, resulting in changes to the test vectors and hence it currently breaks the python timing tests.
