### ISSUE TITLE
Put/Post is forbiddon from ...

### ISSUE THREAD

**Issue by nilsbuc** [PandABlocks/PandABlocks-FPGA#202]
Hey,
I tried to use the commandline with venv and I followed this tutorial ( https://pandablocks.github.io/PandABlocks-client/master/tutorials/installation.html ). I didn't get far, because after loading the tutorial I got a ton of error messages for every block used in the tutorial. I still tried "pandablocks control <hostname>" to control the PandA and it more or less worked. However when I try to use the GUI now I get the message "_**Failed to write to attribute PANDA,design on block PANDA (ValueError: Put/Post is forbidden from xxx.xxx.xxx.xxx)**_". 
I already restartet and rebooted the PandA, I even set it up again, still the same error message. After I set the panda up again, I can at least use the GUI on another pc.
I would really appreciate it, if someone could help me.
I'm using python 3.12.3 and Ubuntu 24.04

**Comment by nilsbuc** [comment]
I can still change the layout by connecting to the tcp server via netcat.

**Comment by coretl** [comment]
If you load this zpkg onto the system then it won't do the subnet check so will get rid of that error message:
https://github.com/PandABlocks/PandABlocks-webcontrol/releases/download/2.1/panda-webcontrol-no-subnet-validation@2.1.zpg

**Comment by nilsbuc** [comment]
Thank you, everything works again.
