### ISSUE TITLE
How to get the input with the FMC_ACQ430

### ISSUE THREAD

**Issue by nilsbuc** [PandABlocks/PandABlocks-FPGA#203]
Hey,
I have a signal generator hooked up to the fmc_acq430 module with a 5Vpp 50kHz sine-wave. 
I have no idea how I can read the value inputted into the fmc_acq430 and there aren't many blocks to which I can connect the val outputs. 
Are there more block librarys or do I have to create my own blocks? I'm pretty sure I have to this anyway some time in the future but I would like to skip it for now, cause I only want to see, that I can capture some input.
Also if there are more blocks, how do I get the .ini files onto the panda?

**Comment by coretl** [comment]
Is the value scaled correctly and appearing in `http://<panda-ip>:8008/gui/PANDA/positions`? Here is a screenshot from a PandA that doesn't have that card, but it should appear in the list somewhere:

![Screenshot from 2024-08-21 14-31-12](https://github.com/user-attachments/assets/879fc46f-4c95-4fe7-a1ed-53dcfdb6f686)

**Comment by nilsbuc** [comment]
Yes, I think I have I have the values scaled correctly, but there is still nothing on the val output. I also put the Signal into an oscilloscope to be sure that the signal is correct, but everything seems fine.
I even tried other signals, like square and pulse, but there's also nothing.
![Screenshot from 2024-08-27 10-15-00](https://github.com/user-attachments/assets/e1740ff2-a6b1-4974-b370-d4cd38ea3065)
![Screenshot from 2024-08-27 10-16-42](https://github.com/user-attachments/assets/c0e1aa1d-1a44-4b4d-ba2e-25924c16f788)

**Comment by nilsbuc** [comment]
I tried to add the value of two different sin signals (one with 5 Vpp and one with 10 Vpp). I captured val5 and val8, cause that are the two inputs I use and also CALC1.OUT for the result. But as you can see, I don't even got any Input from the FMC_ACQ430_IN.
I also tested the ttl of the FMC_ACQ430_IN, which works, so I don't think, that it's broken.
![Screenshot from 2024-08-27 12-50-50](https://github.com/user-attachments/assets/1f44ccc7-b31b-4894-b688-b184646525b3)
![Screenshot from 2024-08-27 12-55-24](https://github.com/user-attachments/assets/cb8e7494-92fb-4330-9acf-4821cdd1ba44)

**Comment by nilsbuc** [comment]
It works now, but I just took the Module out and put it back in and then restartet the PandA. Now I just have a lot of Noise on the inputs. 
![Screenshot from 2024-08-28 09-57-21](https://github.com/user-attachments/assets/1acfa0e4-fbda-4e84-8908-74e9afd92756)
