### ISSUE TITLE
Add standard deviation mode for pcap captures

### ISSUE THREAD

**Issue by thomascobb** [PandABlocks/PandABlocks-FPGA#62]
The FPGA side of https://github.com/PandABlocks/PandABlocks-server/issues/13

Still to do:
- [ ]  Conclude timing investigations to find out if the extra pipelining can be removed from the ADC code and put in PCAP data production
- [x] Add a FPGA_CAPABILITIES register here: https://github.com/PandABlocks/PandABlocks-FPGA/blob/219f430a7c1a23c5157965ab228415753af43265/common/templates/registers_server#L35 and implement bit 0 of it to say whether the FPGA firmware supports std_dev or not

@shu-soleil has partially implemented this on the pcap_std_dev branch.

**Comment by Araneidae** [comment]
Talking to @thomascobb, the suggestion was that we add a new `*REG` register with name `FPGA_CAPABILITY` at register offset 15.  This offset puts this new register out of the `PCAP_` range, and is available.

Register 15 was last used for `SLOW_REGISTER_STATUS`, removed in server commit [7d58b31](https://github.com/PandABlocks/PandABlocks-server/commit/7d58b3191f1f366e20fcc70fc4e5332444a776e8), March 2017, and around commit da98c88a408fbc34b77d637267345b74dfb12409, same time, for this repository.
