### ISSUE TITLE
INENC SSI on a Control card shows connected when it isn't

### ISSUE THREAD

**Issue by coretl** [PandABlocks/PandABlocks-FPGA#89]
Not sure if this is a limitation of the protocol or not, to be tested

**Comment by glennchid** [comment]
According to the logic INENC_CONN should be tied to zero for SSI with a Control. @coretl is DCARD_TYPE reading back correctly as 'Encoder Control'?

**Comment by tomtrafford** [comment]
Update to show connected when it is connected, if possible.

**Comment by glennchid** [comment]
It turns out that INENC_CONN for the MONITOR card claims to be connected when nothing is plugged in to it.
See PR.
